import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import MainWrapper from "./components/layout/MainWrapper";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "MED Link",
  description: "Generated by create next app",
  icons: [{ url: "/images/logo2.jpg", type: "image/png" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="/images/doc1.png" />
      </Head>
      <body className={cairo.className}>
        <Toaster position="top-center" />
        <div>
          <Header />
          <MainWrapper>
            <AuthProvider>{children}</AuthProvider>
          </MainWrapper>
          <Footer />
        </div>
      </body>
    </html>
  );
}
